name: E2E in custom container
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: npm
      - name: Pull down dependencies
        run: npm install
      - name: Build
        run: npm run build:init && npm run build
        
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v3
        with:
          record: true
          browser: chrome
          build: npm run build
          start: npm start
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
